config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  resources :posts do
      resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create, :edit, :update]

  get 'users/:id/edit_password', to: 'users#edit_password', as: :edit_password_user

  patch 'users/:id/change_password', to: 'users#change_password', as: :change_password_user

  resource :session, only: [:create, :new, :destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.is_admin?
      can :manage, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    alias_action :create, :read, :update, :delete, to: :crud
    alias_action :edit, :update, :edit_password, :change_password, to: :update_user

    can :crud, Post do |p|
      user == p.user
    end

    can :destroy, Comment do |c|
      user == c.user || user == c.post.user
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, uniqueness: true
    validates :body, presence: true, length: {minimum: 50}

    belongs_to :user

    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord

    validates :email, presence: true, uniqueness: true, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/ }

    has_secure_password

    has_many :posts, dependent: :nullify
    has_many :comments, dependent: :nullify


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private
    def current_user
        @current_user ||= User.find_by_id(session[:user_id])
    end
    helper_method :current_user

    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?

    def authenticated_user!
        redirect_to new_session_path, {alert: "You are not logged in!"} unless user_signed_in?
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_post
    before_action :authenticated_user!
    
    def create
        @comment = Comment.new(params.require(:comment).permit(:body))
        @comment.post = @post
        @comment.user = current_user

        if @comment.save
            flash[:notice] = "Comment created successfully!"
            redirect_to post_path(@post)
        else
            flash[:alert] = "Cannot create comment!"
            @comments = @post.comments.order(created_at: :desc)
            render "/posts/show", status: 303
        end
        
    end

    def destroy
        @comment = Comment.find(params[:id])
        if can?(:destroy, @comment)
            if @comment.destroy
                flash[:notice] = "Comment deleted successfully!"
            else
                flash[:alert] = "Cannot deleted comment!"
            end
            redirect_to post_path(@post)
        else
            redirect_to post_path(@post), alert: "Not authorized"
        end
    end

    private
    def find_post
        @post = Post.find(params[:post_id])
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy]
    before_action :authenticated_user!, except: [:show, :index]
    before_action :authorize_user!, only:[:edit, :update, :destroy]
    
    def new
        @post = Post.new
    end

    def create
        @post = Post.new(get_params)
        @post.user = current_user
        if @post.save
            flash[:notice] = "Post created successfully."
            redirect_to post_path(@post)
        else
            render "/posts/new", status: 303
        end
    end

    def index
        @posts = Post.order(created_at: :desc)

    end

    def show
        @comments = @post.comments.order(created_at: :desc)
        @comment = Comment.new
    end

    def edit

    end

    def update
        if @post.update(get_params)
            flash[:notice] = "Post updated successfully."
            redirect_to post_path(@post)
        else
            render :edit
        end
    end

    def destroy
        if @post.destroy
            flash[:notice] = "Post deleted successfully."
            redirect_to posts_path
        else
            flash[:alert] = "Cannot delete post!"
        end
    end

    private
    def find_post
        @post = Post.find(params[:id])
    end
    
    def get_params
        params.require(:post).permit(:title, :body)
    end

    def authorize_user!
        redirect_to root_path, alert: "Not authorized" unless can?(:crud, @post)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        
    end

    def create
        @user = User.find_by_email params[:email]

        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            flash.notice = "Logged In"
            redirect_to root_path
          else
            render :new, {alert: "Wrong email or password!", status: 303}
        end

    end

    def destroy
        session[:user_id] = nil;
        flash.notice = "Logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticated_user!, except: [:new, :create]
    before_action :get_user, except: [:new, :create]
    before_action :authorize_user!, except: [:new, :create]

    def new
        @user = User.new
    end

    def create
        @user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path
        else
            render :new, status: 303
        end
    end

    def edit

    end

    def update
        if @user.update(params.require(:user).permit(:name, :email))
            flash[:notice] = "User has been updated"
            redirect_to root_path
        else
            flash[:alert] = "User cannot be updated"
            render :edit, status: 303
        end
    end

    def edit_password

    end

    def change_password
        if @user && @user.authenticate(params[:current_password]) && !same_password?
            password = params[:new_password]
            password_confirmation = params[:new_password_confirmation]
            if @user.update(password: password, password_confirmation: password_confirmation)
                flash[:notice] = "Password has been updated"
                redirect_to root_path
            else
                render :edit_password, status: 303
            end
        else
            flash[:notice] = "Your current password is wrong or you cannot use same password!"
            render :edit_password, status: 303
        end
    end

    private
    def same_password?
        params[:current_password] == params[:new_password]
    end

    def get_user
        @user = current_user
    end

    def authorize_user!
        redirect_to root_path, alert: "Not authorized" unless params[:id].to_i == current_user.id
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar"%>
    <br>
    <% flash.each do |type, message| %>
      <% if type == "notice"%>
        <div class="alert alert-info mx-3" role="alert">
          <%= message %>
        </div>
      <% else %>
          <div class="alert alert-danger mx-3" role="alert">
          <%= message %>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%=render "shared/post_form"%>

app/views/posts/index.html.erb
    <div class="row row-cols-3 ms-3">
        <% @posts.each do |p| %>
            <div class="card col m-3 py-3" style="width: 28rem;">
                <div class="card-body">
                    <h5 class="card-title"><a href="<%=post_path(p)%>" class="text-decoration-none"><%= p.title%></a></h5>
                    <p class="card-text text-truncate"><%= p.body%></p>
                </div>
            </div>
        <% end %>
    </div>

app/views/posts/new.html.erb
<%= render "shared/post_form"%>

app/views/posts/show.html.erb
<div class="mt-2 ms-3" style="width: 30rem;">
  <div class="card-body p-0">
    <h1 class="card-title"><%= @post.title%></h1>
    <p class="card-text text-break"><%= @post.body%></p>
    <span><small>Posted <%= time_ago_in_words(@post.created_at) %> ago</small></span>
    <div class="d-flex flex-row mt-3">
        <a href="<%= edit_post_path(@post)%>" class="btn btn-outline-primary me-2">Edit</a>
        <%= button_to 'Delete',post_path(@post), method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}}, class:"btn btn-outline-primary me-2"%>
    </div>
  </div>
</div>
<br>
<div class="mt-3 ms-3" style="width: 30rem;">
  <h4>Comment</h4>
  <%= bootstrap_form_with(model: [@post, @comment]) do |f|%>
      <%=f.text_area :body, rows:3, placeholder: "What's in your mind?", hide_label: true%>
      <%=f.submit "Submit", class: "btn btn-outline-primary" %>
  <% end %>
</div>

<% @comments.each do |comment| %>
  <div class="my-3 ms-3" style="width: 30rem;">
    <p class="m-0 lh-sm text-break"><%= comment.body%></p>
    <span class="d-flex flex-row align-items-end"><small style="font-size: 12px;">Commented <%= time_ago_in_words(comment.created_at) %> ago&emsp;|&emsp;</small>
    <small><%= button_to "Delete", post_comment_path(@post, comment), method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}}, class:"btn btn-link m-0 p-0 border-0 text-decoration-none",style:"font-size: 12px;"%></small></span>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Blog On Rails</a>
    <div class="d-flex flex-row" id="navbarSupportedContent">
      <ul class="navbar-nav d-flex flex-row justify-content-evenly mb-2 mb-lg-0 ">
        <li class="nav-item mx-3">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item mx-3">
          <a class="nav-link active" href="<%=new_post_path%>">New Post</a>
        </li>
        <li class="nav-item mx-3 d-flex d-flex-direction-row align-items-baseline">
          <% if user_signed_in? %>
            <span class="d-flex d-flex-direction-row align-items-baseline me-3">Hi, <a class="nav-link active" href="<%= edit_user_path(current_user)%>"> <%= current_user.name %></a></span>
            <%= button_to "Sign Out", session_path, method: :delete, class: "btn btn-outline-primary"%>
          <% else %>
            <a class="nav-link active me-3" href="<%=new_session_path%>">Sign In</a>
            <a class="nav-link active" href="<%=new_user_path%>">Sign Up</a>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_post_form.html.erb
<div class="mt-3 ms-3" style="width: 30rem;">
    <% if @post.errors.any? %>
        <div class="alert alert-danger">
            <p>Please fix the errors below.</p>
            <ul class="rails-bootstrap-forms-error-summary">
                <% @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div>
        <%= bootstrap_form_with(model: @post) do |f|%>
            <%=f.text_field :title%>
            <%=f.text_area :body, rows:5%>
            <% if @post.id %>
                <%= f.submit "Update Post", class: "btn btn-outline-primary" %>
            <% else %>
                <%= f.submit "Create Post", class: "btn btn-outline-primary" %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<div class="mt-3 ms-3" style="width: 30rem;">
    <% if @user.errors.any? %>
        <div class="alert alert-danger">
            <p>Please fix the errors below.</p>
            <ul class="rails-bootstrap-forms-error-summary">
                <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div>
        <%= bootstrap_form_with(model: @user) do |f|%>
            <%=f.text_field :name%>
            <%=f.text_field :email%>
            <%= f.submit "Update Profile", class: "btn btn-outline-primary" %>
            <%= link_to "Change Password", edit_password_user_path(@user), class:"btn btn-outline-primary"%>
        <% end %>
    </div>
</div>

app/views/users/edit_password.html.erb
<div class="mt-3 ms-3" style="width: 30rem;">
    <% if @user && @user.errors.any? %>
        <div class="alert alert-danger">
            <p>Please fix the errors below.</p>
            <ul class="rails-bootstrap-forms-error-summary">
                <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <%= bootstrap_form_with(url: change_password_user_path, method: :patch) do |f|%>
        <%=f.password_field :current_password%>
        <%=f.password_field :new_password %>
        <%=f.password_field :new_password_confirmation %>
        <%= f.submit "Change Password", class: "btn btn-outline-primary" %>
    <% end %>
</div>

app/views/users/new.html.erb
<div class="mt-3 ms-3" style="width: 30rem;">
    <% if @user.errors.any? %>
        <div class="alert alert-danger">
            <p>Please fix the errors below.</p>
            <ul class="rails-bootstrap-forms-error-summary">
                <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div>
        <%= bootstrap_form_with(model: @user) do |f|%>
             <%=f.text_field :name%>
            <%=f.text_field :email%>
            <%=f.password_field :password %>
            <%=f.password_field :password_confirmation %>
            <%= f.submit "Register", class: "btn btn-outline-primary" %>
        <% end %>
    </div>
</div>